version: '3.3'

services:
  income:
    image: yohimbe/calendar_backend:v2
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:80"
    restart: always
