name: calendar_income workflow

on: [push]

jobs:
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push backend to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/calendar_backend:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }} 
          script: |
            sudo docker pull yohimbe/calendar_backend:v1
            sudo docker-compose stop
            sudo docker-compose rm backend
            sudo rm .env
            touch .env

            echo TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} >> .env
            echo TELEGRAM_TO=${{ secrets.TELEGRAM_TO }} >> .env
            echo SCOPES=${{ secrets.SCOPES }} >> .env
            echo FILE_PATH=${{ secrets.FILE_PATH }} >> .env
            echo CALENDAR_ID=${{ secrets.CALENDAR_ID }} >> .env
